### ISSUE TITLE
MockInjectingStrategy

### ISSUE THREAD

**Issue by amalbuquerque** [skylerparr/syringe#1]
Found your syringe in a blog post comment and it was exactly what I was looking for, but I'm unable to run the tests with the mocked modules, even for a simple example like the following: [Syringe_Mocktest_example.zip](https://github.com/skylerparr/syringe/files/764331/Syringe_Mocktest_example.zip)

Relevant code (Module that should be mocked):
```
defmodule MyS3 do
  def upload(content, %{} = new_doc) do
    IO.puts "S3: UPLOADING #{content} #{inspect(new_doc)}"
    {:ok, :uploaded}
  end
end
```

Module using the previous one:
```
defmodule Mocktest do
  use Injector

  inject MyS3, as: InjectedS3

  def hello do
    InjectedS3.upload("some_content", %{uuid: "THIS-IS-A-UUID"})
    :world
  end
end
```

And the test:
```
defmodule MocktestTest do
  use ExUnit.Case, async: true
  import Mocker

  test "basic stuff" do
    mock(MyS3)
    intercept(MyS3, :upload, ["some content", %{uuid: "THIS-IS-A-UUID"}], with: fn (_, _) -> IO.puts "INTERCEPTING :upload" end)

    assert Mocktest.hello == :world
    assert was_called(MyS3, :upload, ["some content", %{uuid: "THIS-IS-A-UUID"}]) == once()
  end
end
```

It fails on the last assertion, MyS3.upload was never called. Am I missing something?

Thanks in advance, and one more time, awesome work!

Can you please check the attached code? Thanks!

**Comment by skylerparr** [comment]
That one threw me for a loop. But I tracked down your problem. In your intercept call you're matching:
```
["some content", %{uuid: "THIS-IS-A-UUID"}]
```
But in your implementation:
```
InjectedS3.upload("some_content", %{uuid: "THIS-IS-A-UUID"})
```
```
"some content" != "some_content"
```
So it was unable to match the first argument.

Let me know if you have anymore issues.

**Comment by amalbuquerque** [comment]
You're completely right, sorry for the dumb mistake.
