### ISSUE TITLE
Compilation error with multiple injectors for same module

### ISSUE THREAD

**Issue by ndemonner** [skylerparr/syringe#2]
I have two Plugs, which both need to mock the same Ecto repo:

```
defmodule API.Plug.Authn do
  use Injector
  alias Plug.Conn
  inject SomeService.Repo, as: Repo
  ...
```

```
defmodule API.Plug.Authz do
  use Injector
  alias Plug.Conn
  inject SomeService.Repo, as: Repo
  ...
```

When compiled, I get this error:

```== Compilation error on file lib/api/plug/auth_plug.ex ==
** (CompileError) lib/api/plug/authz_plug.ex:12: cannot define module Injector.SomeService.Repo because it is currently being defined in lib/api/plug/authn_plug.ex:10
    lib/api/plug/auth_plug.ex:12: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

I'm going to keep debugging, but I figured you might be able to point me in the right direction quickly.

**Comment by skylerparr** [comment]
I've run into this before. It's related to the way the mock modules are
created at compile time. Try `mix clean` to see if that helps. If not, let
me know and I'll see if I can work something out.

**Comment by ndemonner** [comment]
Yeah, `mix clean` doesn't seem to help.

https://github.com/SenecaSystems/syringe/commit/41bf4b880d41291a7fa82be09e5973d0c27f1cf5 sort of fixes it (allows the app to compile and run tests successfully), but issues this warning:

```
warning: this clause cannot match because a previous clause at line 10 always matches
  lib/api/plug/authn_plug.ex:3
```

**Comment by skylerparr** [comment]
That warning is unrelated. It's a known issue I've been working on. I'm waiting on SenecaSystems to submit a PR and I'll release.

**Comment by ndemonner** [comment]
I think this should be closed now that the bug is fixed, but maybe open a new one for the warning issue?
