### ISSUE TITLE
Error resolving struct defined in mocked module

### ISSUE THREAD

**Issue by boydm** [skylerparr/syringe#5]
When I mock a module (HTTPoison) so that I can intercept a response from the server without actually calling it, I get an error later in saying that the compiler cannot resolve the `Injector.HTTPoison.Response` same with the  `Injector.HTTPoison.Error` struct.

It should be resolving `HTTPoison.Response` and `HTTPoison.Error` structs instead.

Original function:

```elixir
  def call_auth_server( url, json ) do
    case HTTPoison.post( url, json, [@json_header] ) do
      {:ok, %HTTPoison.Response{body: body, status_code: 200}} ->
        {:ok, body}

      {:ok, %HTTPoison.Response{body: body, status_code: status_code}} when status_code >= 500 ->
        {:server_error, status_code, "internal_server_error"}

      {:ok, %HTTPoison.Response{body: body, status_code: status_code} = resp} ->
        {:ok, data} = Poison.decode( body )
        {:server_error, status_code, data["reason"] || to_string(status_code)}

      err ->
        err
    end
  end
```

Test function:

```elixir
  test "call_auth_server calls the server and returns a the body" do
    mock(HTTPoison)
    intercept(HTTPoison, :post, nil, with: fn() -> {:ok, @server_response_200} end)
    assert Token.call_auth_server("url", "json") == {:ok, @server_body}
  end
```

Where @server_response_200 and @server_body are sensible maps of data.

The command line error is:

```
== Compilation error in file lib/socket/token.ex ==
** (CompileError) lib/socket/token.ex:101: Injector.HTTPoison.Response.__struct__/0 is undefined, cannot expand struct Injector.HTTPoison.Response
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
```

**Comment by skylerparr** [comment]
Are you injecting the structs too? or just injecting the HTTPoison module?

**Comment by boydm** [comment]
Just the module.

**Comment by boydm** [comment]
```
defmodule K10.Socket.Token do
  use Injector
  require Logger

  alias K10.Socket

  # same as alias in dev. allows mocking in test via syringe Injector
  inject HTTPoison

  import IEx

```

**Comment by boydm** [comment]
```
  inject HTTPoison
  inject HTTPoison.Response
  inject HTTPoison.Error
```

got me past that issue, but it seems clunky. Would be nice if `inject` auto injected structs...

**Comment by skylerparr** [comment]
I see what you're getting at. Structs are kind of a weird thing to inject. With structs, I generally just alias them since mocking a struct isn't defined.

**Comment by boydm** [comment]
No wait. It's worse than that.

I can't match on the response type.

The original code here does this...

```
    case HTTPoison.post( url, json, [@json_header] ) do
      {:ok, %HTTPoison.Response{body: body, status_code: 200}} ->
        {:ok, body}
```

This match works in dev, but fails in test because it would need to match against `Injector.HTTPoison.Response `

**Comment by boydm** [comment]
It works if I define the response to be 

```elixir
  @server_response_200 %Injector.HTTPoison.Response{
    body: @server_body,
    status_code: 200
  }
```
 in the test code. That was non-intuitive, needing at least something in the readme.

**Comment by skylerparr** [comment]
Do you get the same result if you `alias` the structs? If you alias the structs, do a `mix clean` since the code it generated a compile time.

**Comment by boydm** [comment]
In the test file, I tried this first `alias Injector.HTTPoison`, but that didn't work because then the `mock(HTTPoison)` call fails as it tries to `mock(Injector.HTTPoison)`

Next, I tried aliasing the structs (again in the test file) individually, like this:
```elixir
  alias Injector.HTTPoison.Response
  alias Injector.HTTPoison.Error
```

That allows the mock function to work, but prevents me from using things like
```elixir
  @server_response_400 %HTTPoison.Response{
    body: @reason_400,
    status_code: 404
  }
```

which is more readable (and less ambiguous) than 
```elixir
  @server_response_400 %Response{
    body: @reason_400,
    status_code: 404
  }
```
even tho that last one works.

**Comment by skylerparr** [comment]
what about aliasing the structs without the `Injector.` prefix? I'm pretty sure your code will right now will fail when not in `MIX_ENV=test`.

With my projects I inject the functional modules and alias the structs. Eg:

```
defmodule MyModule do
  use Injector
 
  inject HTTPoison

  alias HTTPoison.Response
  alias HTTPoison.Error

  #etc
end
```

Then in the tests, I alias normally.

**Comment by boydm** [comment]
I'll try that.

Although, that forces me to use `Response` and `Error` in the functional code instead of `HTTPoison.Response` and `HTTPoison.Error`, which are more readable and less ambiguous...

**Comment by boydm** [comment]
Is there a way to make this work?

```elixir
  inject HTTPoison
  alias HTTPoison
```

Such that `HTTPoison.Response` aliases to the correct thing in test?

**Comment by boydm** [comment]
Otherwise, yes, aliasing `HTTPoison.Response` and `HTTPoison.Error` works, but leaves the code less readable.

**Comment by skylerparr** [comment]
Unfortunately the inject just behaves as alias when not in `MIX_ENV=test`, so effectively those two directives are exactly the same. I know it seems kinda janky, but you can specify the `as` to the same module:
```
alias HTTPoison.Response, as: HTTPoison.Response
```
If you desire the prefix. 

I feel like your original approach should just work regardless. I'll take a look deeper into why it doesn't.

**Comment by boydm** [comment]
Drat. That doesn't work.

```
== Compilation error in file lib/socket/token.ex ==
** (CompileError) lib/socket/token.ex:17: invalid value for option :as, expected a simple alias, got nested alias: HTTPoison.Response
```

**Comment by boydm** [comment]
More playing with it...

The only model that works in both environments is...

```elixir
  inject HTTPoison
  inject HTTPoison.Response
  inject HTTPoison.Error
```

Unless I'm wrong...    :-P

**Comment by skylerparr** [comment]
There isn't anything technically wrong with that approach. Under the hood `inject` literally translates to an `alias`. The downside is that it implies that it can be mocked at test time. Also, it may create an issue with running an assertion against the struct in test unless it's aliased with `Injector.` prefix. Does that make sense?

**Comment by boydm** [comment]
Yes. Makes sense.

On the test side, I'm doing this

```elixir
  alias Injector.HTTPoison.Response
  alias Injector.HTTPoison.Error
```

To alleviate the assertion problem.
